// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-BbdWe0wV7BxmvLHcdYotTxrgoRjKtY',
    appId: '1:631093038984:web:0785fa69b18d819935343d',
    messagingSenderId: '631093038984',
    projectId: 'tca-backend-62a10',
    authDomain: 'tca-backend-62a10.firebaseapp.com',
    storageBucket: 'tca-backend-62a10.appspot.com',
    measurementId: 'G-65YR8F0QC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CxTIoyUyt0Cez6wl9Oa82DxDeP-H3Kw',
    appId: '1:631093038984:android:af214e845ffbed9435343d',
    messagingSenderId: '631093038984',
    projectId: 'tca-backend-62a10',
    storageBucket: 'tca-backend-62a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8ILD1pVFp99mjPdHTSL6VbNlkbVru5k',
    appId: '1:631093038984:ios:864b4edcf4f6a82935343d',
    messagingSenderId: '631093038984',
    projectId: 'tca-backend-62a10',
    storageBucket: 'tca-backend-62a10.appspot.com',
    iosClientId: '631093038984-vtjoqhk1nr656ec6di4beo8hldlgu9te.apps.googleusercontent.com',
    iosBundleId: 'inc.novi.tca.tca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8ILD1pVFp99mjPdHTSL6VbNlkbVru5k',
    appId: '1:631093038984:ios:864b4edcf4f6a82935343d',
    messagingSenderId: '631093038984',
    projectId: 'tca-backend-62a10',
    storageBucket: 'tca-backend-62a10.appspot.com',
    iosClientId: '631093038984-vtjoqhk1nr656ec6di4beo8hldlgu9te.apps.googleusercontent.com',
    iosBundleId: 'inc.novi.tca.tca',
  );
}
